### ISSUE TITLE
The test cases pass for both success as well as faliure scenarios

### ISSUE THREAD

**Issue by pgAdmin** [mdb/flickr-feeder#2]
expect(JSON.parse(data).some_key).to.eql('some_value');

expect(JSON.parse(data).some_key).to.eql('some__value_1');

Both of them pass without throwing any error.

**Comment by mdb** [comment]
@pgAdmin Thanks for pointing this out! This code is obviously fairly old. Would you like to confirm that PR #3 addresses this bug?

**Comment by mdb** [comment]
@pgAdmin I'm going to close this issue; I've checked in a fix via PR #3. Please let me know if you disagree. Thanks!

**Comment by pgAdmin** [comment]
@mdb That works fine! :+1:
